name: store_api
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  logger: ^1.1.0
  test: ^1.16.0
  mongo_dart: ^0.7.4
  shelf_static: ^1.1.0
  shelf_router: ^1.1.2
  shelf: ^1.2.0
  shelf_hotreload: ^1.3.0

  #user registration
  uuid: ^3.0.6
  crypto: ^3.0.2
  path: ^1.8.2

  json_serializable: ^6.4.1
  json_annotation: ^4.7.0
  build_runner: ^2.2.1


